export const TodoActionTypes = {
  CREATE_TODO: "CREATE_TODO",
  REMOVE_TODO: "REMOVE_TODO",
  COMPLETED_TODO: "COMPLETED_TODO",
  LOAD_TODOS_START: "LOAD_TODOS_START",
  LOAD_TODOS_SUCCESS: "LOAD_TODOS_SUCCESS",
  LOAD_TODOS_FAILURE: "LOAD_TODOS_FAILURE",
};
